FROM python:3.10
USER root

# uvのインストール
COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin/uv

RUN apt-get update && \
    pip install --upgrade pip && \
    apt-get install -y git curl gnupg && \
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg \
      | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg && \
    chmod go+r /usr/share/keyrings/githubcli-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" \
      | tee /etc/apt/sources.list.d/github-cli.list > /dev/null && \
    apt-get update && \
    apt-get install -y gh


WORKDIR /workspace

# その他便利ツールのインストール
# RUN apt-get -y install --reinstall ca-certificates && \
#     apt-get -y install software-properties-common && \
#     apt-get install -y sudo wget vim curl gawk make gcc && \
#     apt-get install -y graphviz xdg-utils && \
#     apt-get install iputils-ping net-tools
